#!/usr/bin/env python3
from __future__ import annotations

import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from v7_contract_registry import (  # noqa: E402
    ContractRegistry,
    contract_from_market,
    make_settlement_reference,
    normalize_rules,
    parse_chainlink_twap_source,
)


def market(source: str = "https://data.chain.link/streams/btc-usd-twap-60s-streams") -> dict:
    return {
        "id": "market-1",
        "eventId": "event-1",
        "conditionId": "condition-1",
        "slug": "btc-updown-5m-test",
        "question": "BTC Up or Down 5m",
        "rules": (
            "This market resolves Up when the time-weighted average price (TWAP) of Bitcoin, "
            "generated by Chainlink for the stated range, is greater than or equal to the price "
            "at the beginning of that range. Otherwise it resolves Down. The Chainlink source is "
            "authoritative; this is not according to other sources or spot markets."
        ),
        "resolutionSource": source,
        "tokens": [
            {"outcome": "Up", "token_id": "yes-token"},
            {"outcome": "Down", "token_id": "no-token"},
        ],
        "feeSchedule": {"rate": 0.01, "exponent": 2.0, "takerOnly": True},
        "startDate": "2026-08-28T18:00:00Z",
        "endDate": "2026-08-28T18:05:00Z",
    }


def main() -> None:
    asset, quote, window, canonical = parse_chainlink_twap_source(
        "https://data.chain.link/streams/btc-usd-twap-60s-streams"
    )
    assert (asset, quote, window) == ("BTC", "USD", 60)
    assert canonical.endswith("btc-usd-twap-60s-streams")

    raw = market()
    spec = contract_from_market(raw)
    assert spec.verified_template is True
    assert spec.oracle_window_seconds == 60
    assert spec.comparator == "GREATER_EQUAL"
    assert spec.rules_hash_recognized is False
    assert spec.informed_trading_authorized is False
    assert normalize_rules(raw["rules"]) == spec.normalized_rules

    with tempfile.TemporaryDirectory() as tmp:
        registry = ContractRegistry(Path(tmp) / "registry.json")
        registry.approve_rule_hash(spec, evidence="prospective operator verification against market rules")
        registry.save()
        approved = contract_from_market(raw, approved_rule_hashes=registry.approved_rule_hashes)
        assert approved.rules_hash_recognized is True
        assert approved.informed_trading_authorized is True

        reference = make_settlement_reference(
            approved,
            exact_value="63742.123456789",
            observation_timestamp_ns=100,
            receive_monotonic_ns=110,
            source_state_version=3,
            reference_version=4,
            provenance="same-oracle Chainlink BTC/USD TWAP report",
        )
        assert reference.valid is True
        assert reference.reference_value_exact == "63742.123456789"
        assert reference.oracle_window_seconds == 60
        hot = reference.hot_projection()
        assert hot["reference_value_numeric"] == 63742.123456789
        assert hot["valid"] == 1

    changed = market()
    changed["rules"] = changed["rules"].replace("greater than or equal to", "greater than")
    changed_spec = contract_from_market(changed, approved_rule_hashes={spec.normalized_rules_hash})
    assert changed_spec.comparator == "GREATER"
    assert changed_spec.normalized_rules_hash != spec.normalized_rules_hash
    assert changed_spec.rules_hash_recognized is False

    source_30 = contract_from_market(market("https://data.chain.link/streams/btc-usd-twap-30s-streams"))
    assert source_30.verified_template is True
    assert source_30.oracle_window_seconds == 30
    assert source_30.contract_version != spec.contract_version

    unknown = market("https://example.com/btc-usd")
    unknown_spec = contract_from_market(unknown)
    assert unknown_spec.verified_template is False
    assert unknown_spec.informed_trading_authorized is False


if __name__ == "__main__":
    main()
