#include "poly/engine.hpp"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>

namespace poly {
namespace {std::string now_iso(){auto n=std::chrono::system_clock::now();auto t=std::chrono::system_clock::to_time_t(n);std::tm tm{};
#ifdef _WIN32
 gmtime_s(&tm,&t);
#else
 gmtime_r(&t,&tm);
#endif
 std::ostringstream os;os<<std::put_time(&tm,"%Y-%m-%dT%H:%M:%SZ");return os.str();}}

QuantEngine::QuantEngine(EngineConfig c):cfg_(c),client_(),model_(c),risk_(c),broker_(c.initial_capital),last_equity_(c.initial_capital){std::filesystem::create_directories("runs");model_.load_history("runs/history.csv");}
void QuantEngine::set_external_csv(const std::string&p){external_.load_csv(p);}
TradeIdea QuantEngine::make_idea(const LiveMarket&m,const FairValue&f)const{double qy=f.probability,qn=1-qy,ye=m.yes_book.best_ask,ne=m.no_book.best_ask;TradeIdea i;i.market_id=m.market.id;i.question=m.market.question;i.uncertainty=f.uncertainty;if(qy-ye>=qn-ne){i.token_id=m.market.yes_token;i.outcome="YES";i.fair_probability=qy;i.entry_price=ye;i.raw_edge=qy-ye;}else{i.token_id=m.market.no_token;i.outcome="NO";i.fair_probability=qn;i.entry_price=ne;i.raw_edge=qn-ne;}double r=m.market.fees.live?m.market.fees.rate:cfg_.fallback_taker_fee_rate,e=m.market.fees.live?m.market.fees.exponent:cfg_.fallback_taker_fee_exponent;double fee=platform_fee_per_share(i.entry_price,r,e),slip=i.entry_price*cfg_.slippage_bps/10000.0,other=i.entry_price*cfg_.assumed_fee_bps/10000.0;i.estimated_cost=fee+slip+other+cfg_.uncertainty_buffer*f.uncertainty;i.net_edge=i.raw_edge-i.estimated_cost;return i;}
void QuantEngine::append_signal_log(const TradeIdea&i,const FairValue&f)const{bool fresh=!std::filesystem::exists("runs/signals.csv");std::ofstream o("runs/signals.csv",std::ios::app);if(fresh)o<<"time,market_id,outcome,fair,entry,raw_edge,cost,net_edge,uncertainty,question\n";std::string q=i.question;std::replace(q.begin(),q.end(),',',';');o<<now_iso()<<','<<i.market_id<<','<<i.outcome<<','<<f.probability<<','<<i.entry_price<<','<<i.raw_edge<<','<<i.estimated_cost<<','<<i.net_edge<<','<<i.uncertainty<<','<<q<<'\n';}
void QuantEngine::append_fill_log(const PaperFill&f,const std::string&reason)const{bool fresh=!std::filesystem::exists("runs/fills.csv");std::ofstream o("runs/fills.csv",std::ios::app);if(fresh)o<<"time,action,market_id,token_id,outcome,shares,price,principal,fee,cash_after,reason\n";o<<now_iso()<<','<<f.action<<','<<f.market_id<<','<<f.token_id<<','<<f.outcome<<','<<f.shares<<','<<f.price<<','<<f.principal<<','<<f.fee<<','<<f.cash_after<<','<<reason<<'\n';}
void QuantEngine::write_status(const std::vector<LiveMarket>&u)const{std::ofstream o("runs/status.json");o<<"{\n  \"time\": \""<<now_iso()<<"\",\n  \"paper\": true,\n  \"markets\": "<<u.size()<<",\n  \"equity\": "<<last_equity_<<",\n  \"drawdown\": "<<risk_.drawdown(last_equity_)<<",\n  \"killed\": "<<(risk_.killed()?"true":"false")<<",\n  \"cash\": "<<broker_.cash()<<",\n  \"positions\": "<<broker_.positions().size()<<",\n  \"ideas\": "<<last_ideas_.size()<<"\n}\n";}
void QuantEngine::run_once(){auto u=client_.snapshot(cfg_.market_limit,cfg_.min_liquidity,cfg_.max_spread);if(u.empty())throw std::runtime_error("no live tradable markets returned after filters");std::unordered_map<std::string,double>px;std::unordered_map<std::string,std::string>m2e;std::unordered_map<std::string,const LiveMarket*>by_id;for(const auto&m:u){px[m.market.yes_token]=m.yes_book.midpoint();px[m.market.no_token]=m.no_book.midpoint();m2e[m.market.id]=m.market.event_id;by_id[m.market.id]=&m;}
    std::unordered_map<std::string,FairValue>fair;std::unordered_map<std::string,TradeIdea>idea;for(const auto&m:u){auto f=model_.predict(m,u,external_);auto x=make_idea(m,f);fair[m.market.id]=f;idea[m.market.id]=x;append_signal_log(x,f);}
    auto existing=broker_.positions();for(const auto&p:existing){auto mi=by_id.find(p.market_id);if(mi==by_id.end())continue;const auto&m=*mi->second;const auto&f=fair.at(p.market_id);double sf=p.outcome=="YES"?f.probability:1-f.probability,bid=p.outcome=="YES"?m.yes_book.best_bid:m.no_book.best_bid;bool opposite=idea.at(p.market_id).token_id!=p.token_id&&idea.at(p.market_id).net_edge>=cfg_.min_net_edge;bool overvalued=sf+cfg_.exit_edge<bid;if(opposite||overvalued){double r=m.market.fees.live?m.market.fees.rate:cfg_.fallback_taker_fee_rate,e=m.market.fees.live?m.market.fees.exponent:cfg_.fallback_taker_fee_exponent;if(auto fill=broker_.close_token(p.market_id,p.token_id,p.outcome,bid,r,e,cfg_.slippage_bps))append_fill_log(*fill,opposite?"opposite_signal":"fair_below_bid");}}
    last_equity_=broker_.marked_equity(px);risk_.update_equity(last_equity_);last_ideas_.clear();for(const auto&m:u){auto x=idea.at(m.market.id);if(x.net_edge>=cfg_.min_net_edge)last_ideas_.push_back(x);}std::sort(last_ideas_.begin(),last_ideas_.end(),[](const auto&a,const auto&b){double sa=a.net_edge/std::max(.01,a.uncertainty),sb=b.net_edge/std::max(.01,b.uncertainty);return sa>sb;});
    for(auto&x:last_ideas_){if(risk_.killed())break;const auto&m=*by_id.at(x.market_id);double n=risk_.allowed_notional(x,last_equity_,broker_.gross_value(px),broker_.market_exposure(x.market_id,px),broker_.event_exposure(m.market.event_id,m2e,px),broker_.worst_case_loss(px));x.desired_notional=n;if(n<=0)continue;double r=m.market.fees.live?m.market.fees.rate:cfg_.fallback_taker_fee_rate,e=m.market.fees.live?m.market.fees.exponent:cfg_.fallback_taker_fee_exponent;if(auto fill=broker_.buy(x,n,r,e,cfg_.slippage_bps)){append_fill_log(*fill,"entry");last_equity_=broker_.marked_equity(px);risk_.update_equity(last_equity_);}}
    model_.update_history(u);last_equity_=broker_.marked_equity(px);risk_.update_equity(last_equity_);write_status(u);
    std::cout<<"\nPOLYMARKET UNIVERSAL ENGINE — PAPER ONLY\nmarkets="<<u.size()<<" equity="<<std::fixed<<std::setprecision(2)<<last_equity_<<" cash="<<broker_.cash()<<" positions="<<broker_.positions().size()<<" drawdown="<<100*risk_.drawdown(last_equity_)<<"% killed="<<(risk_.killed()?"YES":"no")<<"\n";std::cout<<std::left<<std::setw(9)<<"market"<<std::setw(5)<<"side"<<std::setw(9)<<"entry"<<std::setw(9)<<"fair"<<std::setw(10)<<"netEdge"<<std::setw(11)<<"notional"<<"question\n";for(std::size_t k=0;k<std::min<std::size_t>(10,last_ideas_.size());++k){const auto&i=last_ideas_[k];std::cout<<std::setw(9)<<i.market_id.substr(0,8)<<std::setw(5)<<i.outcome<<std::setw(9)<<std::setprecision(4)<<i.entry_price<<std::setw(9)<<i.fair_probability<<std::setw(10)<<i.net_edge<<std::setw(11)<<std::setprecision(2)<<i.desired_notional<<i.question.substr(0,75)<<'\n';}}

} // namespace poly
