#include "poly/engine.hpp"

#include <algorithm>
#include <cmath>
#include <cctype>
#include <fstream>
#include <limits>
#include <numeric>
#include <sstream>

namespace poly {
namespace {double logit(double p){p=std::clamp(p,.001,.999);return std::log(p/(1-p));}double wmean(const std::vector<std::pair<double,double>>&x,double f){double n=0,d=0;for(auto[a,w]:x){n+=a*w;d+=w;}return d?n/d:f;}}

void ExternalSignalStore::load_csv(const std::string& path){std::ifstream in(path);if(!in)throw std::runtime_error("cannot open external signal CSV: "+path);std::string s;std::getline(in,s);while(std::getline(in,s)){if(s.empty()||s[0]=='#')continue;std::stringstream ss(s);std::string id,p,c,src;std::getline(ss,id,',');std::getline(ss,p,',');std::getline(ss,c,',');std::getline(ss,src);try{set(id,{clamp_probability(std::stod(p)),std::clamp(std::stod(c),0.0,1.0),src,std::chrono::system_clock::now()});}catch(...){}}}
void ExternalSignalStore::set(const std::string&id,ExternalSignal s){signals_[id]=std::move(s);}std::optional<ExternalSignal>ExternalSignalStore::get(const std::string&id)const{auto i=signals_.find(id);return i==signals_.end()?std::nullopt:std::optional<ExternalSignal>(i->second);}
std::vector<double> hash_text_embedding(const std::string& text,std::size_t dim){std::vector<double>v(dim);std::string t;auto flush=[&]{if(t.size()<2){t.clear();return;}uint64_t h=1469598103934665603ULL;for(unsigned char c:t){h^=c;h*=1099511628211ULL;}v[h%dim]+=((h>>8)&1)?1.0:-1.0;t.clear();};for(unsigned char c:text){if(std::isalnum(c))t.push_back(static_cast<char>(std::tolower(c)));else flush();}flush();double n=std::sqrt(std::inner_product(v.begin(),v.end(),v.begin(),0.0));if(n)for(auto&x:v)x/=n;return v;}
double cosine_similarity(const std::vector<double>&a,const std::vector<double>&b){return a.size()==b.size()&&!a.empty()?std::inner_product(a.begin(),a.end(),b.begin(),0.0):0;}double clamp_probability(double p){return std::clamp(p,.001,.999);}double platform_fee_per_share(double p,double r,double e){if(r<=0)return 0;p=std::clamp(p,.001,.999);return r*std::pow(p*(1-p),std::max(0.0,e));}

UniversalModel::UniversalModel(EngineConfig c):cfg_(c){}
void UniversalModel::load_history(const std::string& path){history_path_=path;std::ifstream in(path);std::string s;while(std::getline(in,s)){std::stringstream ss(s);std::string ts,id,px;std::getline(ss,ts,',');std::getline(ss,id,',');std::getline(ss,px,',');try{auto&h=price_history_[id];h.push_back(std::stod(px));while(h.size()>cfg_.factor_history)h.pop_front();}catch(...){}}}
std::size_t UniversalModel::history_size(const std::string&id)const{auto i=price_history_.find(id);return i==price_history_.end()?0:i->second.size();}
void UniversalModel::update_history(const std::vector<LiveMarket>&u){std::ofstream o;if(!history_path_.empty())o.open(history_path_,std::ios::app);auto ts=std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();for(const auto&m:u){auto&h=price_history_[m.market.id];h.push_back(m.yes_book.midpoint());while(h.size()>cfg_.factor_history)h.pop_front();if(o)o<<ts<<','<<m.market.id<<','<<m.yes_book.midpoint()<<'\n';}}
ExpertPrediction UniversalModel::microstructure(const LiveMarket&m)const{const auto&b=m.yes_book;if(b.bids.empty()||b.asks.empty())return{"micro",.5,0,false};double d=b.bid_depth+b.ask_depth,imb=d?(b.bid_depth-b.ask_depth)/d:0;double fair=clamp_probability(b.midpoint()+.35*b.spread()*imb),sc=std::clamp(1-b.spread()/cfg_.max_spread,0.0,1.0),dc=std::clamp(std::log1p(d)/std::log(10001.0),0.0,1.0);return{"micro",fair,.25+.55*sc*dc,true};}
ExpertPrediction UniversalModel::factor(const LiveMarket&m,const std::vector<LiveMarket>&u)const{std::vector<const LiveMarket*>a;std::size_t common=std::numeric_limits<std::size_t>::max();for(const auto&x:u){auto i=price_history_.find(x.market.id);if(i==price_history_.end()||i->second.size()<cfg_.min_factor_history)continue;a.push_back(&x);common=std::min(common,i->second.size());}if(a.size()<3||common<cfg_.min_factor_history)return{"pca_factor",.5,0,false};common=std::min(common,cfg_.factor_history);std::size_t n=a.size(),k=common-1,target=n;std::vector<std::vector<double>>r(n,std::vector<double>(k));std::vector<double>mu(n);for(std::size_t i=0;i<n;++i){if(a[i]->market.id==m.market.id)target=i;const auto&h=price_history_.at(a[i]->market.id);auto off=h.size()-common;for(std::size_t t=0;t<k;++t){r[i][t]=logit(h[off+t+1])-logit(h[off+t]);mu[i]+=r[i][t];}mu[i]/=k;for(auto&x:r[i])x-=mu[i];}if(target==n)return{"pca_factor",.5,0,false};std::vector<std::vector<double>>C(n,std::vector<double>(n));for(std::size_t i=0;i<n;++i)for(std::size_t j=i;j<n;++j){for(std::size_t t=0;t<k;++t)C[i][j]+=r[i][t]*r[j][t];C[i][j]/=std::max<std::size_t>(1,k-1);C[j][i]=C[i][j];}std::vector<double>v(n,1/std::sqrt(double(n)));for(int z=0;z<30;++z){std::vector<double>w(n);for(std::size_t i=0;i<n;++i)for(std::size_t j=0;j<n;++j)w[i]+=C[i][j]*v[j];double q=std::sqrt(std::inner_product(w.begin(),w.end(),w.begin(),0.0));if(q<1e-12)return{"pca_factor",.5,0,false};for(std::size_t i=0;i<n;++i)v[i]=w[i]/q;}std::vector<double>cr(n);for(std::size_t i=0;i<n;++i){const auto&h=price_history_.at(a[i]->market.id);cr[i]=logit(a[i]->yes_book.midpoint())-logit(h.back())-mu[i];}double f=std::inner_product(v.begin(),v.end(),cr.begin(),0.0),res=cr[target]-v[target]*f,rss=0;for(std::size_t t=0;t<k;++t){double ft=0;for(std::size_t i=0;i<n;++i)ft+=v[i]*r[i][t];double e=r[target][t]-v[target]*ft;rss+=e*e;}double sd=std::sqrt(rss/std::max<std::size_t>(1,k-1)+1e-10),z=std::abs(res)/sd,fl=logit(m.yes_book.midpoint())-.35*res,fair=1/(1+std::exp(-fl));double conf=(.12+.38*std::clamp(z/3,0.0,1.0))*std::clamp(double(n)/20,0.0,1.0);return{"pca_factor",clamp_probability(fair),conf,true};}
ExpertPrediction UniversalModel::graph(const LiveMarket&m,const std::vector<LiveMarket>&u)const{if(!m.market.neg_risk||m.market.event_id.empty())return{"graph",.5,0,false};std::vector<const LiveMarket*>g;for(const auto&x:u)if(x.market.neg_risk&&x.market.event_id==m.market.event_id)g.push_back(&x);if(g.size()<2)return{"graph",.5,0,false};double s=0;for(auto*x:g)s+=x->yes_book.midpoint();if(s<.90||s>1.10)return{"graph",.5,0,false};return{"graph",clamp_probability(m.yes_book.midpoint()/s),.25+.45*std::min(1.0,std::abs(s-1)/.10),true};}
ExpertPrediction UniversalModel::semantic_relative_value(const LiveMarket&m,const std::vector<LiveMarket>&u)const{std::vector<std::pair<double,double>>n;for(const auto&x:u)if(x.market.id!=m.market.id){double s=cosine_similarity(m.text_embedding,x.text_embedding);if(s>=.72)n.emplace_back(x.yes_book.midpoint(),s*s);}if(n.size()<2)return{"semantic_rv",.5,0,false};double cur=m.yes_book.midpoint();return{"semantic_rv",clamp_probability(.85*cur+.15*wmean(n,cur)),std::min(.30,.08+.03*n.size()),true};}
ExpertPrediction UniversalModel::external_signal(const LiveMarket&m,const ExternalSignalStore&e)const{auto s=e.get(m.market.id);if(!s)return{"external",.5,0,false};auto age=std::chrono::duration_cast<std::chrono::hours>(std::chrono::system_clock::now()-s->timestamp).count();return{"external",clamp_probability(s->probability),std::clamp(s->confidence*std::exp(-std::max<long long>(0,age)/48.0),0.0,1.0),true};}
double UniversalModel::expert_weight(const ExpertPrediction&p)const{double b=.25;auto n=expert_brier_n_.find(p.expert);if(n!=expert_brier_n_.end()&&n->second)b=expert_brier_sum_.at(p.expert)/n->second;return p.confidence*std::exp(-cfg_.ensemble_eta*b);}
FairValue UniversalModel::predict(const LiveMarket&m,const std::vector<LiveMarket>&u,const ExternalSignalStore&e){FairValue f;f.components={microstructure(m),factor(m,u),graph(m,u),semantic_relative_value(m,u),external_signal(m,e)};double n=0,d=0;for(const auto&p:f.components)if(p.active&&p.confidence>0){double w=expert_weight(p);n+=w*p.probability;d+=w;}f.probability=clamp_probability(d?n/d:m.yes_book.midpoint());double v=0;if(d){for(const auto&p:f.components)if(p.active&&p.confidence>0){double w=expert_weight(p),x=p.probability-f.probability;v+=w*x*x;}v/=d;}f.uncertainty=std::clamp(std::sqrt(v)+.15*std::clamp(m.yes_book.spread()/cfg_.max_spread,0.0,1.0),.005,.5);last_prediction_[m.market.id]=f;return f;}
void UniversalModel::observe_resolution(const std::string&id,bool yes){auto i=last_prediction_.find(id);if(i==last_prediction_.end())return;double y=yes?1:0;for(const auto&p:i->second.components)if(p.active){expert_brier_sum_[p.expert]+=(p.probability-y)*(p.probability-y);++expert_brier_n_[p.expert];}}

} // namespace poly
