#include "poly/engine.hpp"
#include <algorithm>
#include <cmath>

namespace poly {
RiskManager::RiskManager(EngineConfig c):cfg_(c),peak_equity_(c.initial_capital){}
double RiskManager::drawdown(double e)const{return peak_equity_>0?std::max(0.0,1-e/peak_equity_):0;}
void RiskManager::update_equity(double e){peak_equity_=std::max(peak_equity_,e);if(drawdown(e)>=cfg_.max_drawdown)killed_=true;}
double RiskManager::allowed_notional(const TradeIdea&i,double e,double gross,double market,double event,double open_loss)const{if(killed_||e<=0||i.net_edge<=0)return 0;double rb=std::max(0.0,cfg_.max_gross_fraction*e-gross),mb=std::max(0.0,cfg_.max_market_fraction*e-market),eb=std::max(0.0,cfg_.max_event_fraction*e-event),tb=cfg_.max_trade_fraction*e;double p=std::clamp(i.entry_price,.001,.999),q=std::clamp(i.fair_probability,.001,.999),kb=cfg_.kelly_fraction*std::max(0.0,(q-p)/(1-p))*e;double loss_from_peak=std::max(0.0,peak_equity_-e),dd_room=std::max(0.0,cfg_.max_drawdown*peak_equity_-loss_from_peak-open_loss);return std::max(0.0,std::min({rb,mb,eb,tb,kb,dd_room}));}

PaperBroker::PaperBroker(double c):cash_(c){}
std::optional<PaperFill> PaperBroker::buy(const TradeIdea&i,double principal,double r,double exp,double slip_bps){if(principal<=0||i.entry_price<=0)return std::nullopt;double fill=std::min(.999,i.entry_price*(1+slip_bps/10000.0)),shares=principal/fill,fee=shares*platform_fee_per_share(fill,r,exp),total=principal+fee;if(total>cash_){double scale=cash_/total;principal*=scale;shares*=scale;fee*=scale;total=cash_;}if(principal<=0)return std::nullopt;auto it=std::find_if(positions_.begin(),positions_.end(),[&](const auto&p){return p.token_id==i.token_id;});if(it==positions_.end())positions_.push_back({i.market_id,i.token_id,i.outcome,shares,principal,fee});else{it->shares+=shares;it->cost+=principal;it->fees_paid+=fee;}cash_-=total;return PaperFill{"BUY",i.market_id,i.token_id,i.outcome,shares,fill,principal,fee,cash_};}
std::optional<PaperFill> PaperBroker::close_token(const std::string&mid,const std::string&tok,const std::string&outcome,double bid,double r,double exp,double slip_bps){double fill=std::max(.001,bid*(1-slip_bps/10000.0)),shares=0;for(const auto&p:positions_)if(p.token_id==tok)shares+=p.shares;if(shares<=0)return std::nullopt;double principal=shares*fill,fee=shares*platform_fee_per_share(fill,r,exp);cash_+=std::max(0.0,principal-fee);positions_.erase(std::remove_if(positions_.begin(),positions_.end(),[&](const auto&p){return p.token_id==tok;}),positions_.end());return PaperFill{"SELL",mid,tok,outcome,shares,fill,principal,fee,cash_};}
double PaperBroker::marked_equity(const std::unordered_map<std::string,double>&px)const{double e=cash_;for(const auto&p:positions_){auto i=px.find(p.token_id);double m=i==px.end()?p.cost/std::max(p.shares,1e-12):i->second;e+=p.shares*m;}return e;}
double PaperBroker::gross_value(const std::unordered_map<std::string,double>&px)const{double x=0;for(const auto&p:positions_){auto i=px.find(p.token_id);x+=p.shares*(i==px.end()?p.cost/std::max(p.shares,1e-12):i->second);}return x;}
double PaperBroker::worst_case_loss(const std::unordered_map<std::string,double>&px)const{return gross_value(px);}double PaperBroker::market_exposure(const std::string&id,const std::unordered_map<std::string,double>&px)const{double x=0;for(const auto&p:positions_)if(p.market_id==id){auto i=px.find(p.token_id);x+=p.shares*(i==px.end()?p.cost/std::max(p.shares,1e-12):i->second);}return x;}
double PaperBroker::event_exposure(const std::string&e,const std::unordered_map<std::string,std::string>&m2e,const std::unordered_map<std::string,double>&px)const{if(e.empty())return 0;double x=0;for(const auto&p:positions_){auto m=m2e.find(p.market_id);if(m!=m2e.end()&&m->second==e){auto i=px.find(p.token_id);x+=p.shares*(i==px.end()?p.cost/std::max(p.shares,1e-12):i->second);}}return x;}
bool PaperBroker::owns_token(const std::string&t)const{return std::any_of(positions_.begin(),positions_.end(),[&](const auto&p){return p.token_id==t&&p.shares>0;});}
} // namespace poly
